### ISSUE TITLE
Latest Episodes for Anime Unavailable 

### ISSUE THREAD

**Issue by siker498** [Matheus-0/Anime-Twist#11]
For many of the animes, the latest episodes are unavailable, like episode 162 of black clover, The new season of Log Horizon is missing 5 episodes, and Re: Zero is missing two new episodes. . Any chance you could add other sources other than twist.moe, like gogoanime or animepahe? The app is fantastic I just wished episode releases were up to date.

**Comment by Matheus-0** [comment]
I noticed it when I went to watch Re:Zero, ended up going to watch somewhere else.
Unfortunately, I made this app to be exclusive to Anime Twist's content, so I won't add other sources (also I don't have much time right now because of college). I hope they'll add the new episodes soon.
