### ISSUE TITLE
Opening/ending skip button in player

### ISSUE THREAD

**Issue by sgrxrx** [Matheus-0/Anime-Twist#13]
The app is simple and i prefer it over what they call their "official app" but what i have a issue with is not having a anime opening/ending button with a +85 sec time skip and a "sreen locking" button ( idk what they call it, but you probably get it). Anyway great app. Thank you.

**Comment by Matheus-0** [comment]
I will implement the player locking feature. As for the opening/ending skipping, I'll think about it, but no promises, I'd prefer to have access to an API with the actual timestamps rather than guessing.

**Comment by Matheus-0** [comment]
Done. It will be available in the next release.

I'll keep this issue open until I decide what to do about the other issue.

**Comment by sgrxrx** [comment]
ah Thanks. Looking forward to it.

**Comment by sgrxrx** [comment]
Finding an api for opening/ending is hard or probably there isn't one. 85sec is what most app out there uses or what most openings/endings are of. Opening/ending ranges from 85-90 sec at most. So 85sec is probably the best. Having a skip button of 85sec is better than having none. Thanks for adding the locking feature. Its helping a lot as i constantly have to check my notifications (swipe down) on my phone. Now it doesn't messes with my volume/brightness. Thank you.

**Comment by Matheus-0** [comment]
I decided not to add it, I know most anime have openings around that duration but I still think it's a half-assed solution, it won't work with a lot of anime that I personally watch.
