### ISSUE TITLE
new animes.

### ISSUE THREAD

**Issue by nahhhbody** [Matheus-0/Anime-Twist#19]
This app has great potential since it's simple and fast. However, new updates or any new animes aren't showing or isn't included in the app. I hope that this app is still being maintained and If so, I look forward to the next update!

**Comment by Matheus-0** [comment]
Hey, I appreciate the feedback. Unfortunately the website I get the videos from (twist.moe) hasn't had its content updated in a long time now, so I stopped making any further updates to the app as it would be kinda pointless (I also currently don't have the time right now to update this app to a new site or to make another one, so I'm sorry).

**Comment by nahhhbody** [comment]
Well it's a shame that this app will no longer have any new updates but anyway, thank you for creating this app and I totally understand. :)
