### ISSUE TITLE
Search anime in api from anime id

### ISSUE THREAD

**Issue by Elismar13** [Matheus-0/Anime-Twist#5]
I need a function to execute a request to the api to return data about that single related anime, is it possible?

Example: GET /api/anime/5454 will return OnePiece anime data

This is necessary to fix a BUG in favorites screen. Outgoing anime keeps with outgoing flag even marked, like Uzaki-chan.
I made a branch to solve this problem, but I need this function.

**Comment by Matheus-0** [comment]
Good catch, I didn't think of that.
I ended up fixing it myself, the fix will be available on the next release.

Commit: b935a32b7237e305ccccc9f0c8ee61cf1923167e
