### ISSUE TITLE
Navigation Buttons. (Android) 

### ISSUE THREAD

**Issue by PrathamModi69** [Matheus-0/Anime-Twist#6]
Hi! I absolutely love the new player but I have a suggestion. When the episode starts playing can the navigation button fade away rather than staying there. It's not a big deal but will surely improve the experience of watching. Thank You for your work.

**Comment by Matheus-0** [comment]
Hey, thanks. Glad you like the app.
I'm aware of the navigation bar problem, actually. Unfortunately I couldn't find a way of hiding them without ejecting the project. I will try to do it in the future but no promises yet.
What you can try to do for now is seeing if your phone has an option to hide it in any way, like after a few seconds without use or something like that.

**Comment by PrathamModi69** [comment]
Thanks for replying! And I don't think my phone has that option but anyways just wanted to throw the light on that issue it doesn't bother me much. :D

**Comment by BIGEAZY289** [comment]
Can we have cast option in the app

**Comment by Matheus-0** [comment]
It's not planned.

**Comment by BIGEAZY289** [comment]
So is it possible to see it in future updates

**Comment by Matheus-0** [comment]
I can't say whether I will do it or not, but probably not.

**Comment by Matheus-0** [comment]
I probably won't do it.
