### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by PrathamModi69** [Matheus-0/Anime-Twist#7]
I love the next episode floating instead of just adding a next episode button. But I do have a suggestion. 
Can the forward and backward button be 5sec instead of 10sec? If not then can you tell me the cons for having a 5 sec button? Because I use those buttons only when I miss an important moment or couldn't read subtitles so the 10 secs every time for the missed 2sec is a bit too much. Thanks, appreciate your hard work :D

**Comment by Matheus-0** [comment]
Hey, I was actually thinking about this recently, 5 seconds is indeed better, you can always just tap twice if you want to go back 10 seconds I guess. I will update it.

And thanks as well, appreciate the support and I'm glad you like the app!

**Comment by PrathamModi69** [comment]
Also I'm sorry I forgot to mention, the series with more than 100 episodes shows episodes till 100 only. Like one piece has 960 episodes but the list shows 100. Bleach has 366 episodes but the list shows 100. Thanks.

**Comment by Matheus-0** [comment]
It's been updated, open you app again and it should be 5 seconds now.
About the 100 episodes, press the floating button at the bottom right and there will be an option to select the range of episodes, I did that for performance reasons.

**Comment by PrathamModi69** [comment]
Oh wow I'm sorry I didn't notice that's a nice feature ;D

**Comment by Matheus-0** [comment]
Glad I could help, and thanks for the suggestion.
I will update the release now and close this issue.
